---

- name: restart caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted
    daemon_reload: yes

- name: reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded
    daemon_reload: no